### ISSUE TITLE
请求追加站点优酷漫画及修复COCOMANHU

### ISSUE THREAD

**Issue by wesleyx2** [hardwarecode/onecomic#2]
优酷漫画地址：https://www.ykmh.com/
好像是原来的漫画堆

另外支持列表里的cocomanhua我试了很多次好像都不能抓取成功，不知道是不是失效了
麻烦也修复一下吧
…………………………………………………………
更新一下 coco原来是我没正确配置，现在已经没问题了

**Comment by yijiepifu** [comment]
> 

coco怎么处理的
