### ISSUE TITLE
建议新增加网站 漫蛙

### ISSUE THREAD

**Issue by wesleyx2** [hardwarecode/onecomic#22]
域名挺多的 
大陆地区 1：
https://manwa.site/
大陆地区 2：
https://manwa.life/
大陆地区 3：
https://manwa.biz/
非大陆地区：
https://manwa.fun/

**Comment by HRX273** [comment]
好

**Comment by HRX273** [comment]
好

**Comment by HRX273** [comment]
非常好

**Comment by njmyder** [comment]
_操_逼_视频,你懂的  [点击进入](https://www.scc5.top/)

_操_逼_视频,你懂的  [点击进入](https://www.scc8.top/)

      
兑才回袄当攘确酶看孕淮殉承筒某凭
