### ISSUE TITLE
包子漫画下载不完整

### ISSUE THREAD

**Issue by Milesday** [hardwarecode/onecomic#24]
1. 

- 包子漫画是分页显示的，一页最多显示50张图片，现在只能下载第一页
- 后续页面的开始四张图片和前一页的最后四张图片是重复的
- 我放三个例子，都是分了四页 [1](https://www.webmota.com/comic/chapter/fangkainagenuwu-yuewenmanhua/0_18.html)、[2](https://www.webmota.com/comic/chapter/fangkainagenuwu-yuewenmanhua/0_19.html)、[3](https://www.webmota.com/comic/chapter/fangkainagenuwu-yuewenmanhua/0_20.html)

2. 下载过程中某些章节可能下载失败，我下了一本500多章的漫画，缺失了5章，不知道能不能做到一次就全部下载成功
或者说下载完之后输出一些提示信息，至少让我知道有失败的（高级批量下载）

最后要谢谢作者，效果确实很棒！！！

**Comment by BeiAduo** [comment]
废话少说，包子漫画 站长也在群里 经常会修改页面规则，导致你下载的图片不正常 换一家漫画吧
