### ISSUE TITLE
请求支持bilibili漫画境外版资源下载

### ISSUE THREAD

**Issue by wesleyx2** [hardwarecode/onecomic#9]
近期bilibili漫画新增了不少境外版漫画
这些漫画都是有些不和谐要素因此国内版都被和谐了很多内容的
不过境外版都是无修改无水印的（虽然购买的价格也是2倍）
使用梯子的话可以浏览到这些漫画
但是用onecomic下载就会提示错误内容，希望能修改支持一下这种的下载

**Comment by nqianaaron** [comment]
境外版也是一样可以下载的，建议在config.ini里面自己加上代理。

**Comment by wesleyx2** [comment]
> 境外版也是一样可以下载的，建议在config.ini里面自己加上代理。

感谢回复，通过设置config.ini后总算可以下载到了
因此此贴关闭
